### ISSUE TITLE
"list index out of range"

### ISSUE THREAD

**Issue by markinfo** [OpenXenManager/openxenmanager#80]
I get message "list index out of range" with fresh installation from GIT and with empty oxc.conf file after a trying to connect to the first server. There is no warning in terminal.

**Comment by markinfo** [comment]
Hi. I have seen there was repaired  "src/OXM/window_menuitem.py"
Could be also be taken attention to this problem. Or how could I debug code that is leading to this issue?

**Comment by dlintott** [comment]
Hi, 

I haven't really had chance to look into the issue yet. Do you still get the error? 

If you do... Is there any more of warning displayed at all? 

If you also install the raven package (pip install raven) it should report any error message direct to  my Sentry server.

**Comment by oliveiraped** [comment]
Hi, I have the same issue, but its strange, i think it problably diferent versions of xen hypevisor. In one i just connect with no problem, in anther system that error appeared.

**Comment by winst0nsmith** [comment]
same problem with openxenmanager r80. is this fixed in latest commits?

i am happy to help debug, if you can let me know how to do so...

**Comment by PrestonR** [comment]
I'm on OpenXenManager 0.1.0-dev1 cloned and installed from the repo and I'm still getting this error when trying to add new servers. Is there a quick fix for this or should we still help debug?

**Comment by dlintott** [comment]
@winst0nsmith Sorry the delayed response. The r80 version, is hugely buggy... I would try the lastest commit from here, which should be much btter

**Comment by markinfo** [comment]
Just tried version from GIT (0.1.0-dev1) and I can connect to all my Xenservers now.

**Comment by dickensja** [comment]
In case this is helpful, I get this error if I try to connect to a slave server. If I print self.session in oxcServer_addserver.py just after line 57, I get:
{'Status': 'Failure', 'ErrorDescription': ['HOST_IS_SLAVE', '<master_ip>']}
Replacing my connection host to the master as detailed in that error resolves the problem. At least for that event, lines 70-71 also in oxcServer_addserver.py are the immediate cause of the list index out of range error.

**Comment by dlintott** [comment]
@dickensja That is indeed helpful... Gives me a place to start investigating
